sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t pandzior/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pandzior/react-test npm run test -- --coverage

after_success:
  - docker build -t pandzior/multi-client ./client
  - docker build -t pandzior/multi-nginx ./nginx
  - docker build -t pandzior/multi-server ./server
  - docker build -t pandzior/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pandzior/multi-client
  - docker push pandzior/multi-nginx
  - docker push pandzior/multi-server
  - docker push pandzior/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: eu-central-1
#  app: app name
#  env: env name
#  bucket_name: bucket name
#  bucket_path: bucket path
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECURE_KEY